[tool.poetry]
name = "personal-shopping-assistant"
version = "0.1.0"
description = ""
authors = ["Aditya Wagh <waghaditya2707@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
